### ISSUE TITLE
Typings incomplete

### ISSUE THREAD

**Issue by DGolverdingen** [progress/JSDO#100]
For example: JSDOSession missing a lot of properties and methods.

Currently:

![image](https://user-images.githubusercontent.com/29942500/31329827-27859564-acdc-11e7-9ce0-5be56b62fd25.png)

Runtime (4.4.0):

![image](https://user-images.githubusercontent.com/29942500/31329768-ea0ad03c-acdb-11e7-9d55-5530e066f06b.png)

**Comment by edselg** [comment]
Hello,

Thank you for your feedback.
The support for NPM, Promises and TypeScript is a new project and we are still working on it.

We should have additional updates in this repository and the develop repository as part of the work in the future version.

Thanks.

**Comment by DGolverdingen** [comment]
Hi, currenly testing the new npm package @progress/jsdo-core

First problem is missing typings for authentication, I now have to use a string because progress.data.Session does not exists in typings:

![image](https://user-images.githubusercontent.com/29942500/38796334-67fd5906-415b-11e8-85b6-4b5b57fdac78.png)

Please add interface for authenticationModel

**Comment by edselg** [comment]
Hello,

Thank you for reporting the missing interface for AuthenticationModel.
I have added a note to issue #127.

Thanks again.
