### ISSUE TITLE
JQueryPromise interface not compatible with Async / Await 

### ISSUE THREAD

**Issue by DGolverdingen** [progress/JSDO#126]
JQueryPromise interface has a "then" method, this is not valid with Await promise resolving:

![image](https://user-images.githubusercontent.com/29942500/38800835-9051cd58-4168-11e8-88cf-32cbdfed7c26.png)

Please consider not using the JQueryPromise interface at all in the typings. (Please tell me who you think will use jQuery promises in a TypeScript project???)

In this case the getSession method should be rewritten to:

![image](https://user-images.githubusercontent.com/29942500/38802059-c0e54c4e-416b-11e8-9b79-441a65ab7b28.png)

**Comment by edselg** [comment]
Hello,

Sorry for the confusion with the declaration file.
As you found, we are already using ES6 Promises in this version. However, the declaration file was not updated accordingly.
Issue #127 has been filed to fix the issue.

Thank you and regards.
