### ISSUE TITLE
Typings file for the JSDO refers to JQueryPromise instead of native Promise object

### ISSUE THREAD

**Issue by edselg** [progress/JSDO#127]
Typings file for the JSDO refers to JQueryPromise instead of native Promise object:

https://github.com/progress/JSDO/blob/develop/typings/progress.all.d.ts

Notes:
* Interfaces mentioning "JQuery" should be updated.
* Interface getSessionOptions should be renamed to GetSessionOptions.
* Add interface for AuthenticationModel (See issue #126 ).

Related to GitHub issues:
* #100  . Please close when this issue is fixed.
* #126  .

**Comment by joshualan** [comment]
Fixed. The new typings file uses Promises.
