### ISSUE TITLE
Support for JSDO in NodeJS environments that don't allow for creating files

### ISSUE THREAD

**Issue by steinerj** [progress/JSDO#182]
When using the JSDO in server environments that don't allow to create files, the current localStorage emulation breaks, since it persists to files. Since there is no direct need to persist anything written to the localStorage beyond sessions, it should be okay to just use an in-memory emulation.

This should also have positive performance implications.

I'll provide a PR to fix this issue.

**Comment by edselg** [comment]
Internal issue # ADAS-8780.

**Comment by sbschase** [comment]
Julian, was this for a specific customer?

**Comment by steinerj** [comment]
ish... I can tell you via company email. This was more for general Kinvey compatibility, since the Kinvey flex node environment doesn't allow creating the temporary files needed by the "old" implementation. The in-memory implementation should also be faster. 

I believe @joshualan cherry-picked the changes in the current development branch though: https://github.com/progress/JSDO/blob/develop/src/progress.util.js

This PR is likely kaputt anyway, since I hacked a bit about...

**Comment by edselg** [comment]
@sbschase @steinerj 

The changed that were needed were merged by @joshualan as part of PR https://github.com/progress/JSDO/pull/230 .

I think that this issue and the corresponding PR ( https://github.com/progress/JSDO/pull/183 ) can be closed once we add the corresponding tests.

Thank you and regards.

**Comment by sbschase** [comment]
Awesome!

**Comment by joshualan** [comment]
@edselg i know you mentioned that we need to add tests but since all of our tests use node (and our refresh tests are working), i think we can assume that this fix works? If so, I think I can just close this issue.

**Comment by edselg** [comment]
@joshualan 

Certainly, the integration tests do exercise the functionality and are working.
Please check with PO on whether unit tests for the functionality are required.

Thanks.

**Comment by joshualan** [comment]
After a discussion, no unit tests are required. If everything still works, everything still works. The tests we have verify this behaviour.
