### ISSUE TITLE
JSDO 5.0.0 getData()

### ISSUE THREAD

**Issue by FordAVDev1** [progress/JSDO#191]
We have been using 4.4.1 and I made a update branch. I right off saw an error regarding jsdo.getData(). Is this function no longer supported? I was able to drill down on the jsdo its self and get to the date, so connectivity was working fine.

**Comment by edselg** [comment]
Hello,

Thank you for posting the issue.
The function jsdo.getData() is supported. 

I am guessing that the issue that you are seeing is due the change in the Promises handle between 4.4.1 and 5.0.0.
JSDO 4.4.1 uses jQuery Promises. The signature for handlers is the following fn(jsdo, success, request).
JSDO 5.0.0 uses ES6 Promises. The signature for the handlers is the following fn(object)
To access the jsdo reference you would use object.jsdo.
In your particular case, you could use object.jsdo.getData().

I hope this helps.

**Comment by joshualan** [comment]
@FordAVDev1 Let us know whether @edselg 's answer solved your issue and if you need more help! If not, we're closing and locking this issue.

Thanks!
