### ISSUE TITLE
JSDO not adding tableRef into filter

### ISSUE THREAD

**Issue by chunnybryan** [progress/JSDO#234]
HI 

We have noticed that even though we supply a tableRef property to a DataSource object in our Angular application the JSDO does not add the tableRef into the filter when calling the count invoke or the read / get.

This causes incorrect results or errors for BE's which have multiple tables.

Code example
![image](https://user-images.githubusercontent.com/42641093/52421414-e5a52f80-2aeb-11e9-88f1-66de3f8744df.png)

We are using the JSDO version 6 for Angular with Angular 6.

Thanks

Christian.

**Comment by edselg** [comment]
Hello Christian,

Thank you for reporting the issue.

We will take a look and let you know our findings.

Thank you and regards,
Edsel

**Comment by edselg** [comment]
@chunnybryan 
CC: @consultingwerk

Hello Christian,

I do not think that the enhancement with viewTables was ever submitted as a PR to the JSDO.

We can certainly merge the change to include tableRef and viewTables for the filter.

Mike, could you create a PR for the develop branch with this enhancement?

Thank you and regards,
Edsel

**Comment by chunnybryan** [comment]
HI 
I am going to create a local branch with this change in and push it up to the REPO so i can make PR.
When i try to PUSH my local branch to the REPO i get a permission error does someone need to give me permission to the REPO?
Thanks
Christian.

**Comment by chunnybryan** [comment]
![image](https://user-images.githubusercontent.com/42641093/52706515-82008380-2f7d-11e9-9171-5320f8471030.png)

**Comment by edselg** [comment]
Hello Christian,

Thank you for working on this change.

I think that the right process for this would be to fork the JSDO repo and implement the change in your own repo, then you would be able to submit it as a PR.

Related links:
* https://guides.github.com/activities/forking/
* https://gist.github.com/Chaser324/ce0505fbed06b947d962

Thanks again.

**Comment by chunnybryan** [comment]
HI Edsel 

Okay got it. The PR should be there now.

Thanks

**Comment by edselg** [comment]
Thanks a lot, Christian.

I see the PR. I changed it to merge into the develop branch.
It shows some additional diff but I should be able to merge it.

I hope to merge it soon.

Thanks again,
Edsel

**Comment by edselg** [comment]
Internal issue # ADAS-15442.

**Comment by edselg** [comment]
@chunnybryan @consultingwerk

Hello Christian,

Thank you for submitting this issue and the pull request.

I have merged the pull request and also added a unit test program.

You can run the unit test by using the following steps:
* npm install
* npm run build:jsdo
* mocha ./test/test.tableref_viewtables.js

I noticed that you had not included the initialization of viewTables.
I think that is fine so that viewTables would be an optional property which can be undefined or initialized to a desired value.

This change should be available via npmjs.com in a future release.

Thanks again,
Edsel

**Comment by edselg** [comment]
Pull requests:
- https://github.com/progress/JSDO/pull/236
- https://github.com/progress/JSDO/pull/237
