### ISSUE TITLE
IE 11 compatibility

### ISSUE THREAD

**Issue by mavaanan** [progress/JSDO#262]
Hi,

Latest version of JSDO seems to use arrow functions and they don't seem to work nicely with IE 11
(https://caniuse.com/#feat=arrow-functions): https://github.com/progress/JSDO/blob/master/lib/progress.jsdo.js#L11712

Is there a plan to support IE 11 at all?

-mavaanan

**Comment by zerovian** [comment]
Hi mavaanan,

Can I ask why you're using a web browser that is no longer being moved forward.  Microsoft Edge browser has superseded IE 11, and IE 11 won't be getting any new features.  Only patches and security updates.  Currently it has ~2.5% market share which is quite low.

Is this blocking you?

**Comment by zerovian** [comment]
Closing as there is no response after 18 days.

**Comment by chunnybryan** [comment]
Hi 
Is this issue closed now?

Does anyone know how difficult this would be to resolve?

Thanks

**Comment by edselg** [comment]
@chunnybryan 

Hello Christian,

I do not think that it difficult to resolve per se but it is the balance between using new functionality and supporting old web browsers.
Possible options would be to change arrow function to regular functions or use a transpilation (straight forward change) to generate older compatible JavaScript code (more involved).

Are you also running into this issue with IE11?

Could you provide detail on @zerovian question? Is this a blocking issue for you?

I hope this helps.

Thank you and regards.

**Comment by zerovian** [comment]
Chunny,

You are welcome to submit a pull request.  It isn't difficult to resolve.  But we also don't want to prevent developers from using newer language features by trying to support browsers that are also effectively end of life.

I'd also encourage you update to a modern browser that has support for ES6 features.  Microsoft stopped development on IE 11 years ago, and replaced it with Edge.  Edge development has also been superceded and Microsoft is rebuilding their next browser on Chrome.

**Comment by chunnybryan** [comment]
HI 

Sorry for the delay.

If we use a previous version of the JSDO will this work in IE11?

Thanks

**Comment by edselg** [comment]
@chunnybryan 

Hello,

I am guessing that you need to support a Windows version where Microsoft Edge is not available and Internet Explorer 11 is the most current browser.

Is that the case?

Related link:
* https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer

I did a quick test using JSDO 4.4.1 with IE11 on a Windows 7 SP1 machine and it works:
* https://oemobiledemo.progress.com/jsdo/test001a.html

However, I am not sure if we officially tested it with IE11.
Other areas to test would be BASIC authentication and FORM-based authentication.

Please notice that the most recent version of the JSDO is version 6.
JSDO 5 introduced the usage of built-in JavaScript Promises which are not available in IE11:
* https://caniuse.com/#search=Promises

Please share your experience using JSDO 4.4.1 in your environment or more detail on your needs.

I hope this helps.

**Comment by chunnybryan** [comment]
HI Progress/Jsdo Team

I think this issue has gone away now from my perspective as we are going to
drop support for IE11 in the product.

Thank you very much for your help and support on the issue though!

Christian.
